/**
 * generateRemainingWorkflow
 *
 * Picks up after generation-preview has produced the first scene.
 * Generates remaining scenes server-side, uploading TTS audio and
 * media assets to Supabase Storage so the course is playable on any device.
 */

import { proxyActivities, defineQuery, setHandler } from '@temporalio/workflow';
import type {
  GenerateSingleSceneParams,
  PushSceneToSupabaseParams,
} from '../activities/classroom-generation.activities';
import type {
  GenerateSceneTTSParams,
  GenerateMediaToSupabaseParams,
  FinalizeCourseScenesParams,
} from '../activities/preview-generation.activities';
import type { Scene, Stage } from '@/lib/types/stage';
import type { SceneOutline } from '@/lib/types/generation';
import type { AgentInfo } from '@/lib/generation/pipeline-types';
import type { GenerateClassroomInput } from '@/lib/server/classroom-generation';

// ---------------------------------------------------------------------------
// Activity proxies
// ---------------------------------------------------------------------------

const {
  generateSingleSceneActivity,
  pushSceneToSupabaseActivity,
} = proxyActivities<{
  generateSingleSceneActivity(params: GenerateSingleSceneParams): Promise<Scene | null>;
  pushSceneToSupabaseActivity(params: PushSceneToSupabaseParams): Promise<void>;
}>({
  startToCloseTimeout: '15 minutes',
  retry: {
    maximumAttempts: 2,
    initialInterval: '10s',
    backoffCoefficient: 2,
  },
});

const {
  fetchExistingScenesActivity,
  generateSceneTTSToSupabaseActivity,
  generateMediaToSupabaseActivity,
  finalizeCourseScenesActivity,
} = proxyActivities<{
  fetchExistingScenesActivity(stageId: string): Promise<Scene[]>;
  generateSceneTTSToSupabaseActivity(params: GenerateSceneTTSParams): Promise<Scene>;
  generateMediaToSupabaseActivity(params: GenerateMediaToSupabaseParams): Promise<Scene[]>;
  finalizeCourseScenesActivity(params: FinalizeCourseScenesParams): Promise<void>;
}>({
  startToCloseTimeout: '15 minutes',
  retry: {
    maximumAttempts: 2,
    initialInterval: '10s',
    backoffCoefficient: 2,
  },
});

// ---------------------------------------------------------------------------
// Status types
// ---------------------------------------------------------------------------

export type PreviewJobStatus = 'running' | 'succeeded' | 'failed';

export type PreviewJobStep =
  | 'initializing'
  | 'generating_scenes'
  | 'generating_tts'
  | 'generating_media'
  | 'persisting'
  | 'completed'
  | 'failed';

export interface PreviewWorkflowStatus {
  status: PreviewJobStatus;
  step: PreviewJobStep;
  progress: number;
  message: string;
  scenesGenerated: number;
  totalPending: number;
  /** All scenes generated by this workflow run (excludes pre-existing scenes). */
  completedScenes: Scene[];
  error?: string;
  done: boolean;
}

export const getPreviewStatusQuery =
  defineQuery<PreviewWorkflowStatus>('getPreviewStatus');

// ---------------------------------------------------------------------------
// Workflow input
// ---------------------------------------------------------------------------

export interface GenerateRemainingWorkflowInput {
  stage: Stage;
  outlines: SceneOutline[];
  agents: AgentInfo[];
  completedOrders: number[];
  courseDescription?: string;
  enableTTS?: boolean;
  enableImageGeneration?: boolean;
  enableVideoGeneration?: boolean;
  requirement: string;
}

// ---------------------------------------------------------------------------
// Workflow
// ---------------------------------------------------------------------------

export async function generateRemainingWorkflow(
  args: GenerateRemainingWorkflowInput,
): Promise<void> {
  const {
    stage,
    outlines,
    agents,
    completedOrders,
    courseDescription,
    enableTTS,
    enableImageGeneration,
    enableVideoGeneration,
    requirement,
  } = args;

  // Default to generating all content unless explicitly disabled.
  // Many callers omit these flags, which would otherwise skip audio/media phases.
  const shouldGenerateTTS = enableTTS ?? true;
  const shouldGenerateImages = enableImageGeneration ?? true;
  const shouldGenerateVideo = enableVideoGeneration ?? true;

  // Mutable status exposed via query
  let status: PreviewJobStatus = 'running';
  let step: PreviewJobStep = 'initializing';
  let progress = 0;
  let message = 'Starting scene generation';
  let scenesGenerated = 0;
  let completedScenes: Scene[] = [];
  let errorMessage: string | undefined;

  const completedSet = new Set(completedOrders);
  const pendingOutlines = outlines
    .filter((o) => !completedSet.has(o.order))
    .sort((a, b) => a.order - b.order);
  const totalPending = pendingOutlines.length;

  const chunk = <T,>(arr: T[], size: number): T[][] => {
    const out: T[][] = [];
    for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
    return out;
  };

  // Keep concurrency bounded to avoid overwhelming downstream APIs and workers.
  // Deterministic batching is replay-safe and still yields parallel Temporal activities.
  const SCENE_PARALLELISM = 100;

  setHandler(getPreviewStatusQuery, (): PreviewWorkflowStatus => ({
    status,
    step,
    progress,
    message,
    scenesGenerated,
    totalPending,
    completedScenes,
    error: errorMessage,
    done: status === 'succeeded' || status === 'failed',
  }));

  if (totalPending === 0) {
    status = 'succeeded';
    step = 'completed';
    progress = 100;
    message = 'All scenes already generated';
    return;
  }

  // Minimal GenerateClassroomInput needed by generateSingleSceneActivity
  const minimalInput: GenerateClassroomInput = {
    requirement,
    language: stage.language,
    enableImageGeneration: true, // media handled separately
    enableVideoGeneration: true,
    enableTTS: true, // TTS handled separately
  };

  try {
    // ---- Step 1: Fetch scenes already in Supabase to include in incremental pushes ----
    step = 'initializing';
    progress = 2;
    message = 'Fetching existing course data';

    const existingScenes = await fetchExistingScenesActivity(stage.id);

    // ---- Step 2: Generate each pending scene ----
    step = 'generating_scenes';
    progress = 5;
    message = `Generating ${totalPending} scenes in parallel`;

    const generated: Scene[] = [];
    const outlineChunks = chunk(pendingOutlines, SCENE_PARALLELISM);
    for (const [chunkIndex, outlinesChunk] of outlineChunks.entries()) {
      message = `Generating scenes (batch ${chunkIndex + 1}/${outlineChunks.length})`;
      progress = 5 + Math.floor((chunkIndex / outlineChunks.length) * 55);

      const batchResults = await Promise.all(
        outlinesChunk.map(async (outline) => {
          const scene = await generateSingleSceneActivity({
            outline,
            stage,
            agents,
            input: minimalInput,
          });
          return scene;
        }),
      );

      for (const scene of batchResults) {
        if (scene) generated.push(scene);
      }

      scenesGenerated = generated.length;
      completedScenes = [...generated].sort((a, b) => a.order - b.order);
    }

    // ---- Step 2b: Generate TTS for all generated scenes (optional) ----
    let newScenes: Scene[] = [...generated].sort((a, b) => a.order - b.order);

    if (shouldGenerateTTS && newScenes.length > 0) {
      step = 'generating_tts';
      progress = 62;
      message = `Generating TTS for ${newScenes.length} scenes in parallel`;

      const ttsChunks = chunk(newScenes, SCENE_PARALLELISM);
      const withTts: Scene[] = [];
      for (const [chunkIndex, scenesChunk] of ttsChunks.entries()) {
        progress = 62 + Math.floor((chunkIndex / ttsChunks.length) * 10);
        message = `Generating TTS (batch ${chunkIndex + 1}/${ttsChunks.length})`;

        const results = await Promise.all(
          scenesChunk.map((scene) =>
            generateSceneTTSToSupabaseActivity({
              scene,
              stageId: stage.id,
            }),
          ),
        );
        withTts.push(...results);
        completedScenes = [...withTts].sort((a, b) => a.order - b.order);
      }

      newScenes = withTts.sort((a, b) => a.order - b.order);
    }

    // ---- Step 3: Media generation (optional) ----
    const allScenes = [...existingScenes, ...newScenes].sort((a, b) => a.order - b.order);

    let finalScenes = allScenes;

    if (newScenes.length > 0 && (shouldGenerateImages || shouldGenerateVideo)) {
      step = 'generating_media';
      progress = 75;
      message = 'Generating and uploading media assets';

      finalScenes = await generateMediaToSupabaseActivity({
        scenes: allScenes,
        outlines,
        stageId: stage.id,
      });
      // Update completedScenes with the media-enriched versions
      completedScenes = finalScenes.filter((s) => !completedSet.has(s.order));
    }

    // ---- Step 4: Final Supabase sync with all scenes + asset URLs ----
    step = 'persisting';
    progress = 95;
    message = 'Finalizing course';

    // Ensure content.json is complete even if finalization becomes a no-op.
    await pushSceneToSupabaseActivity({
      stage,
      scenes: finalScenes,
      courseDescription: courseDescription ?? '',
    });

    await finalizeCourseScenesActivity({
      stage,
      scenes: finalScenes,
      courseDescription,
    });

    // Done
    status = 'succeeded';
    step = 'completed';
    progress = 100;
    message = `Generated ${scenesGenerated} scenes`;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    status = 'failed';
    step = 'failed';
    message = 'Generation failed';
    errorMessage = msg;
    throw err;
  }
}
