/**
 * generateRemainingWorkflow
 *
 * Picks up after generation-preview has produced the first scene.
 * Generates remaining scenes server-side, uploading TTS audio and
 * media assets to Supabase Storage so the course is playable on any device.
 */

import { proxyActivities, defineQuery, setHandler } from '@temporalio/workflow';
import type {
  GenerateSingleSceneParams,
  PushSceneToSupabaseParams,
} from '../activities/classroom-generation.activities';
import type {
  GenerateSceneTTSParams,
  GenerateMediaToSupabaseParams,
  FinalizeCourseScenesParams,
} from '../activities/preview-generation.activities';
import type { Scene, Stage } from '@/lib/types/stage';
import type { SceneOutline } from '@/lib/types/generation';
import type { AgentInfo } from '@/lib/generation/pipeline-types';
import type { GenerateClassroomInput } from '@/lib/server/classroom-generation';

// ---------------------------------------------------------------------------
// Activity proxies
// ---------------------------------------------------------------------------

const {
  generateSingleSceneActivity,
  pushSceneToSupabaseActivity,
} = proxyActivities<{
  generateSingleSceneActivity(params: GenerateSingleSceneParams): Promise<Scene | null>;
  pushSceneToSupabaseActivity(params: PushSceneToSupabaseParams): Promise<void>;
}>({
  startToCloseTimeout: '15 minutes',
  retry: {
    maximumAttempts: 2,
    initialInterval: '10s',
    backoffCoefficient: 2,
  },
});

const {
  fetchExistingScenesActivity,
  generateSceneTTSToSupabaseActivity,
  generateMediaToSupabaseActivity,
  finalizeCourseScenesActivity,
} = proxyActivities<{
  fetchExistingScenesActivity(stageId: string): Promise<Scene[]>;
  generateSceneTTSToSupabaseActivity(params: GenerateSceneTTSParams): Promise<Scene>;
  generateMediaToSupabaseActivity(params: GenerateMediaToSupabaseParams): Promise<Scene[]>;
  finalizeCourseScenesActivity(params: FinalizeCourseScenesParams): Promise<void>;
}>({
  startToCloseTimeout: '15 minutes',
  retry: {
    maximumAttempts: 2,
    initialInterval: '10s',
    backoffCoefficient: 2,
  },
});

// ---------------------------------------------------------------------------
// Status types
// ---------------------------------------------------------------------------

export type PreviewJobStatus = 'running' | 'succeeded' | 'failed';

export type PreviewJobStep =
  | 'initializing'
  | 'generating_scenes'
  | 'generating_tts'
  | 'generating_media'
  | 'persisting'
  | 'completed'
  | 'failed';

export interface PreviewWorkflowStatus {
  status: PreviewJobStatus;
  step: PreviewJobStep;
  progress: number;
  message: string;
  scenesGenerated: number;
  totalPending: number;
  /** All scenes generated by this workflow run (excludes pre-existing scenes). */
  completedScenes: Scene[];
  error?: string;
  done: boolean;
}

export const getPreviewStatusQuery =
  defineQuery<PreviewWorkflowStatus>('getPreviewStatus');

// ---------------------------------------------------------------------------
// Workflow input
// ---------------------------------------------------------------------------

export interface GenerateRemainingWorkflowInput {
  stage: Stage;
  outlines: SceneOutline[];
  agents: AgentInfo[];
  completedOrders: number[];
  courseDescription?: string;
  enableTTS?: boolean;
  enableImageGeneration?: boolean;
  enableVideoGeneration?: boolean;
  requirement: string;
}

// ---------------------------------------------------------------------------
// Workflow
// ---------------------------------------------------------------------------

export async function generateRemainingWorkflow(
  args: GenerateRemainingWorkflowInput,
): Promise<void> {
  const {
    stage,
    outlines,
    agents,
    completedOrders,
    courseDescription,
    enableTTS,
    enableImageGeneration,
    enableVideoGeneration,
    requirement,
  } = args;

  // Mutable status exposed via query
  let status: PreviewJobStatus = 'running';
  let step: PreviewJobStep = 'initializing';
  let progress = 0;
  let message = 'Starting scene generation';
  let scenesGenerated = 0;
  let completedScenes: Scene[] = [];
  let errorMessage: string | undefined;

  const completedSet = new Set(completedOrders);
  const pendingOutlines = outlines
    .filter((o) => !completedSet.has(o.order))
    .sort((a, b) => a.order - b.order);
  const totalPending = pendingOutlines.length;

  setHandler(getPreviewStatusQuery, (): PreviewWorkflowStatus => ({
    status,
    step,
    progress,
    message,
    scenesGenerated,
    totalPending,
    completedScenes,
    error: errorMessage,
    done: status === 'succeeded' || status === 'failed',
  }));

  if (totalPending === 0) {
    status = 'succeeded';
    step = 'completed';
    progress = 100;
    message = 'All scenes already generated';
    return;
  }

  // Minimal GenerateClassroomInput needed by generateSingleSceneActivity
  const minimalInput: GenerateClassroomInput = {
    requirement,
    language: stage.language,
    enableImageGeneration: true, // media handled separately
    enableVideoGeneration: true,
    enableTTS: true, // TTS handled separately
  };

  try {
    // ---- Step 1: Fetch scenes already in Supabase to include in incremental pushes ----
    step = 'initializing';
    progress = 2;
    message = 'Fetching existing course data';

    const existingScenes = await fetchExistingScenesActivity(stage.id);
    const newScenes: Scene[] = [];

    // ---- Step 2: Generate each pending scene ----
    step = 'generating_scenes';

    for (const [index, outline] of pendingOutlines.entries()) {
      const progressBase = 5 + Math.floor((index / totalPending) * 70);
      progress = progressBase;
      message = `Generating scene ${index + 1}/${totalPending}: ${outline.title}`;

      const scene = await generateSingleSceneActivity({
        outline,
        stage,
        agents,
        input: minimalInput,
      });

      if (!scene) {
        message = `Scene skipped (generation failed): ${outline.title}`;
        continue;
      }

      // Generate TTS and upload to Supabase Storage
      let finalScene = scene;
      if (enableTTS) {
        step = 'generating_tts';
        finalScene = await generateSceneTTSToSupabaseActivity({
          scene,
          stageId: stage.id,
        });
        step = 'generating_scenes';
      }

      newScenes.push(finalScene);
      scenesGenerated = newScenes.length;
      completedScenes = [...newScenes];

      // Incremental Supabase sync — include all known scenes so content.json is complete
      const allKnownScenes = [...existingScenes, ...newScenes].sort(
        (a, b) => a.order - b.order,
      );
      await pushSceneToSupabaseActivity({
        stage,
        scenes: allKnownScenes,
        courseDescription: courseDescription ?? '',
      });

      progress = 5 + Math.floor(((index + 1) / totalPending) * 70);
      message = `Generated ${scenesGenerated}/${totalPending} scenes`;
    }

    // ---- Step 3: Media generation (optional) ----
    const allScenes = [
      ...existingScenes,
      ...newScenes,
    ].sort((a, b) => a.order - b.order);

    let finalScenes = allScenes;

    if (
      newScenes.length > 0 &&
      (enableImageGeneration || enableVideoGeneration)
    ) {
      step = 'generating_media';
      progress = 77;
      message = 'Generating and uploading media assets';

      finalScenes = await generateMediaToSupabaseActivity({
        scenes: allScenes,
        outlines,
        stageId: stage.id,
      });
      // Update completedScenes with the media-enriched versions
      completedScenes = finalScenes.filter((s) => !completedSet.has(s.order));
    }

    // ---- Step 4: Final Supabase sync with all scenes + asset URLs ----
    step = 'persisting';
    progress = 95;
    message = 'Finalizing course';

    await finalizeCourseScenesActivity({
      stage,
      scenes: finalScenes,
      courseDescription,
    });

    // Done
    status = 'succeeded';
    step = 'completed';
    progress = 100;
    message = `Generated ${scenesGenerated} scenes`;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    status = 'failed';
    step = 'failed';
    message = 'Generation failed';
    errorMessage = msg;
    throw err;
  }
}
