/**
 * LearnWorlds MCP client (server-side only).
 *
 * Connects to a Learnworlds-MCP server (https://github.com/ohneben/Learnworlds-MCP)
 * over stdio (spawning the configured command) or streamable HTTP, and exposes
 * the two high-level operations OpenMAIC needs: connection testing and course
 * structure publishing.
 *
 * Credentials are received per-request from the browser (where they are
 * persisted locally) and are only injected into the spawned process
 * environment / HTTP headers. They are never logged or stored server-side.
 */
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { createLogger } from '@/lib/logger';
import type {
  LearnWorldsMcpConfig,
  LearnWorldsPublishPayload,
  LearnWorldsPublishResult,
  LearnWorldsTestResult,
} from '@/lib/lms/types';
import { learnWorldsAdminCourseUrl, validateLearnWorldsConfig } from '@/lib/lms/types';

const log = createLogger('LearnWorldsMCP');

/** Tool names generated by Learnworlds-MCP from the OpenAPI spec. */
const TOOL_CREATE_COURSE = 'create_course';
const TOOL_CREATE_SECTION = 'create_course_section';

const CONNECT_TIMEOUT_MS = 30_000;
const CALL_TIMEOUT_MS = 60_000;

interface McpTextResult {
  isError?: boolean;
  content?: Array<{ type: string; text?: string }>;
}

/** Extract the JSON body from a Learnworlds-MCP tool result ("HTTP 200 OK\n{...}"). */
export function parseToolResult(result: McpTextResult): {
  ok: boolean;
  status?: number;
  body?: unknown;
  raw: string;
} {
  const text = (result.content ?? [])
    .filter((c) => c.type === 'text' && typeof c.text === 'string')
    .map((c) => c.text)
    .join('\n');
  const match = text.match(/^HTTP (\d{3}) (OK|ERROR)\n?/);
  const status = match ? Number(match[1]) : undefined;
  const rest = match ? text.slice(match[0].length) : text;
  let body: unknown;
  try {
    body = JSON.parse(rest);
  } catch {
    body = rest;
  }
  return { ok: !result.isError && (status === undefined || status < 400), status, body, raw: text };
}

/** Build a sanitized environment for the stdio-spawned MCP server. */
function buildStdioEnv(config: LearnWorldsMcpConfig): Record<string, string> {
  const inherited: Record<string, string> = {};
  // Pass through only benign process context (PATH etc.), not our own secrets.
  for (const key of ['PATH', 'HOME', 'LANG', 'NODE_ENV', 'TMPDIR']) {
    const value = process.env[key];
    if (value) inherited[key] = value;
  }
  return {
    ...inherited,
    MCP_TRANSPORT: 'stdio',
    LEARNWORLDS_BASE_URL: config.baseUrl,
    LEARNWORLDS_API_TOKEN: config.apiToken,
    LEARNWORLDS_CLIENT_ID: config.clientId,
  };
}

async function createConnectedClient(config: LearnWorldsMcpConfig): Promise<Client> {
  const client = new Client({ name: 'openmaic-lms-export', version: '1.0.0' });

  if (config.transport === 'stdio') {
    const transport = new StdioClientTransport({
      command: config.command,
      args: config.args,
      env: buildStdioEnv(config),
      stderr: 'ignore',
    });
    await client.connect(transport, { timeout: CONNECT_TIMEOUT_MS });
  } else {
    const headers: Record<string, string> = {};
    if (config.httpAuthToken) headers.Authorization = `Bearer ${config.httpAuthToken}`;
    const transport = new StreamableHTTPClientTransport(new URL(config.httpUrl), {
      requestInit: { headers },
    });
    await client.connect(transport, { timeout: CONNECT_TIMEOUT_MS });
  }
  return client;
}

async function withClient<T>(
  config: LearnWorldsMcpConfig,
  fn: (client: Client) => Promise<T>,
): Promise<T> {
  const missing = validateLearnWorldsConfig(config);
  if (missing.length > 0) {
    throw new Error(`Incomplete LearnWorlds MCP configuration: ${missing.join(', ')}`);
  }
  const client = await createConnectedClient(config);
  try {
    return await fn(client);
  } finally {
    await client.close().catch(() => {});
  }
}

/** Test connectivity: connect, list tools, and report course-related tools. */
export async function testLearnWorldsConnection(
  config: LearnWorldsMcpConfig,
): Promise<LearnWorldsTestResult> {
  try {
    return await withClient(config, async (client) => {
      const { tools } = await client.listTools();
      const courseTools = tools
        .map((t) => t.name)
        .filter((name) => name.includes('course'))
        .slice(0, 10);
      const required = [TOOL_CREATE_COURSE, TOOL_CREATE_SECTION];
      const missingTools = required.filter((name) => !tools.some((t) => t.name === name));
      if (missingTools.length > 0) {
        return {
          ok: false,
          toolCount: tools.length,
          courseTools,
          error: `MCP server reachable but missing required tools: ${missingTools.join(', ')}`,
        };
      }
      const serverInfo = client.getServerVersion();
      return {
        ok: true,
        serverName: serverInfo?.name,
        serverVersion: serverInfo?.version,
        toolCount: tools.length,
        courseTools,
      };
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    log.warn('Connection test failed', { message });
    return { ok: false, error: message };
  }
}

/** Extract the created course id from a create_course response body. */
export function extractCourseId(body: unknown): { id?: string; titleId?: string } {
  if (!body || typeof body !== 'object') return {};
  const record = body as Record<string, unknown>;
  const data = (record.data ?? record.course ?? record) as Record<string, unknown>;
  const id = typeof data.id === 'string' ? data.id : undefined;
  const titleId = typeof data.titleId === 'string' ? data.titleId : undefined;
  return { id, titleId };
}

/** Publish the course structure (course + sections) to LearnWorlds. */
export async function publishCourseToLearnWorlds(
  config: LearnWorldsMcpConfig,
  course: LearnWorldsPublishPayload,
): Promise<LearnWorldsPublishResult> {
  try {
    return await withClient(config, async (client) => {
      const warnings: string[] = [];

      const createResult = parseToolResult(
        (await client.callTool(
          {
            name: TOOL_CREATE_COURSE,
            arguments: {
              // Learnworlds-MCP nests the HTTP request body under `body`
              // (see buildInputSchema in its tools.ts).
              body: {
                title: course.title,
                titleId: course.titleId,
                description: course.description,
                access: course.access,
              },
            },
          },
          undefined,
          { timeout: CALL_TIMEOUT_MS },
        )) as McpTextResult,
      );

      if (!createResult.ok) {
        const detail =
          typeof createResult.body === 'string'
            ? createResult.body
            : JSON.stringify(createResult.body);
        return {
          ok: false,
          sectionsCreated: 0,
          sectionsFailed: 0,
          warnings,
          error: `create_course failed (HTTP ${createResult.status ?? '?'}): ${detail?.slice(0, 400)}`,
        };
      }

      const { id: courseId, titleId } = extractCourseId(createResult.body);
      const effectiveCourseId = courseId ?? titleId ?? course.titleId;

      let sectionsCreated = 0;
      let sectionsFailed = 0;
      for (const section of course.sections) {
        try {
          const sectionResult = parseToolResult(
            (await client.callTool(
              {
                name: TOOL_CREATE_SECTION,
                arguments: {
                  id: effectiveCourseId,
                  body: { title: section.title, access: 'draft' },
                },
              },
              undefined,
              { timeout: CALL_TIMEOUT_MS },
            )) as McpTextResult,
          );
          if (sectionResult.ok) {
            sectionsCreated += 1;
          } else {
            sectionsFailed += 1;
            warnings.push(
              `Section "${section.title}" failed (HTTP ${sectionResult.status ?? '?'})`,
            );
          }
        } catch (err) {
          sectionsFailed += 1;
          warnings.push(
            `Section "${section.title}" failed: ${err instanceof Error ? err.message : String(err)}`,
          );
        }
      }

      return {
        ok: true,
        courseId: effectiveCourseId,
        courseTitleId: titleId ?? course.titleId,
        adminUrl: learnWorldsAdminCourseUrl(config.baseUrl, effectiveCourseId),
        sectionsCreated,
        sectionsFailed,
        warnings,
      };
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    log.error('Publish failed', { message });
    return { ok: false, sectionsCreated: 0, sectionsFailed: 0, warnings: [], error: message };
  }
}
