-- CreateTable
CREATE TABLE "system_settings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "appName" TEXT NOT NULL DEFAULT 'MU-OpenMAIC',
    "appLogo" TEXT,
    "defaultLanguage" TEXT NOT NULL DEFAULT 'en',
    "timezone" TEXT NOT NULL DEFAULT 'UTC',
    "helpUrl" TEXT,
    "termsUrl" TEXT,
    "privacyUrl" TEXT,
    "passwordMinLength" INTEGER NOT NULL DEFAULT 10,
    "passwordRequireUppercase" BOOLEAN NOT NULL DEFAULT true,
    "passwordRequireLowercase" BOOLEAN NOT NULL DEFAULT true,
    "passwordRequireNumbers" BOOLEAN NOT NULL DEFAULT true,
    "passwordRequireSpecial" BOOLEAN NOT NULL DEFAULT true,
    "sessionTimeoutMinutes" INTEGER NOT NULL DEFAULT 60,
    "maxFailedLoginAttempts" INTEGER NOT NULL DEFAULT 5,
    "accountLockoutMinutes" INTEGER NOT NULL DEFAULT 15,
    "enforceOAuthforNewUsers" BOOLEAN NOT NULL DEFAULT false,
    "pdpaConsentRequired" BOOLEAN NOT NULL DEFAULT true,
    "googleOAuthEnabled" BOOLEAN NOT NULL DEFAULT false,
    "githubOAuthEnabled" BOOLEAN NOT NULL DEFAULT false,
    "defaultLlmProvider" TEXT NOT NULL DEFAULT 'openai',
    "defaultLlmModel" TEXT NOT NULL DEFAULT 'gpt-4o-mini',
    "llmRateLimitPerMinute" INTEGER NOT NULL DEFAULT 60,
    "llmTokenLimitPerRequest" INTEGER NOT NULL DEFAULT 4000,
    "llmTemperature" DOUBLE PRECISION NOT NULL DEFAULT 0.7,
    "llmTopP" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "maxStudentsPerClassroom" INTEGER NOT NULL DEFAULT 100,
    "defaultGradingScale" TEXT NOT NULL DEFAULT '0-100',
    "quizTimeoutMinutes" INTEGER NOT NULL DEFAULT 60,
    "maxFileUploadMb" INTEGER NOT NULL DEFAULT 50,
    "scenesPerClassroomQuota" INTEGER NOT NULL DEFAULT 50,
    "autoEnrollStudents" BOOLEAN NOT NULL DEFAULT false,
    "smtpEnabled" BOOLEAN NOT NULL DEFAULT false,
    "smtpHost" TEXT,
    "smtpPort" INTEGER NOT NULL DEFAULT 587,
    "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
    "smtpUser" TEXT,
    "smtpFrom" TEXT NOT NULL DEFAULT 'noreply@example.com',
    "welcomeEmailEnabled" BOOLEAN NOT NULL DEFAULT true,
    "gradeNotificationsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "maxStoragePerUserMb" INTEGER NOT NULL DEFAULT 1000,
    "maxStoragePerClassroomMb" INTEGER NOT NULL DEFAULT 5000,
    "allowedFileTypes" TEXT NOT NULL DEFAULT '.pdf,.doc,.docx,.xls,.xlsx,.pptx,.jpg,.png,.mp4',
    "autoCleanupDaysOld" INTEGER NOT NULL DEFAULT 365,
    "auditLogRetentionDays" INTEGER NOT NULL DEFAULT 365,
    "userDataExportEnabled" BOOLEAN NOT NULL DEFAULT true,
    "accountDeletionGraceDaysDays" INTEGER NOT NULL DEFAULT 30,
    "anonymizeOldLogs" BOOLEAN NOT NULL DEFAULT false,
    "logLevel" TEXT NOT NULL DEFAULT 'info',
    "errorReportingEnabled" BOOLEAN NOT NULL DEFAULT false,
    "errorReportingUrl" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id")
);
